import { defineConfig } from 'astro/config';
import sitemap from '@astrojs/sitemap';
import { readFileSync } from 'node:fs';

// Legacy redirects (old Jekyll URLs → new) generated by scripts/migrate-content.mjs.
// Astro emits a meta-refresh + canonical HTML page for each, reproducing the
// behaviour of the old _plugins/redirect_generator.rb and the manual .html stubs.
const redirects = JSON.parse(
  readFileSync(new URL('./src/redirects.json', import.meta.url), 'utf-8'),
);

export default defineConfig({
  site: 'https://angelo-lima.fr',
  // All canonical URLs keep their trailing slash, exactly like the Jekyll site.
  trailingSlash: 'always',
  build: { format: 'directory' },
  redirects,
  integrations: [
    sitemap({
      // hreflang alternates are emitted per-page in <head>; the sitemap stays simple & valid.
      // Exclude 404/offline and paginated pages (robots.txt disallows /page/ to avoid duplicates).
      filter: (page) =>
        !page.includes('/404') &&
        !page.includes('/offline') &&
        !/\/page\/\d+\//.test(page),
    }),
  ],
  markdown: {
    gfm: true,
    smartypants: false,
    shikiConfig: {
      theme: 'github-dark',
      wrap: false,
    },
  },
});
