#!/usr/bin/env node
// Downloads the woff2 files for the site's fonts from Google Fonts and generates a
// self-hosted public/assets/css/fonts.css. Self-hosting (same origin) + font-display:swap
// kills the cross-origin FOUT/flicker. Material Symbols is intentionally dropped (unused).

import { writeFileSync, mkdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const FONT_DIR = join(ROOT, 'public', 'assets', 'fonts');
mkdirSync(FONT_DIR, { recursive: true });

const CSS_URL =
  'https://fonts.googleapis.com/css2?family=Playfair+Display:ital,wght@0,400;0,500;0,600;0,700;1,400;1,500&family=Geist:wght@400;500&family=JetBrains+Mono:wght@400;500&display=swap';

// A modern browser UA makes Google return woff2 (not ttf).
const UA =
  'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36';

const css = await (await fetch(CSS_URL, { headers: { 'User-Agent': UA } })).text();

// Collect unique gstatic woff2 URLs.
const urls = [...new Set([...css.matchAll(/url\((https:\/\/fonts\.gstatic\.com\/[^)]+\.woff2)\)/g)].map((m) => m[1]))];
console.log(`Found ${urls.length} woff2 files to download.`);

const nameFor = (u) => u.split('/').pop(); // keep gstatic's unique hashed filename
let localCss = css;

for (const u of urls) {
  const buf = Buffer.from(await (await fetch(u, { headers: { 'User-Agent': UA } })).arrayBuffer());
  const name = nameFor(u);
  writeFileSync(join(FONT_DIR, name), buf);
  localCss = localCss.split(u).join(`/assets/fonts/${name}`);
}

// Drop Google's leading comment noise; keep @font-face blocks as-is (already have font-display:swap).
localCss = `/* Self-hosted fonts (generated by scripts/fetch-fonts.mjs). */\n${localCss}`;
writeFileSync(join(ROOT, 'public', 'assets', 'css', 'fonts.css'), localCss);

console.log(`Wrote public/assets/css/fonts.css (${(localCss.length / 1024).toFixed(0)} KB css).`);

// Print the "latin" subset file for Geist 400 & Playfair 700 so we can <link rel=preload> them.
const faces = localCss.split('@font-face').slice(1);
for (const f of faces) {
  const fam = (f.match(/font-family:\s*'([^']+)'/) || [])[1];
  const weight = (f.match(/font-weight:\s*(\d+)/) || [])[1];
  const italic = /font-style:\s*italic/.test(f);
  const range = (f.match(/unicode-range:\s*([^;]+);/) || [])[1] || '';
  const url = (f.match(/\/assets\/fonts\/[^)]+\.woff2/) || [])[0];
  const isBasicLatin = range.includes('U+0000') || range.includes('U+0000-00FF');
  if (isBasicLatin && !italic && ((fam === 'Geist' && weight === '400') || (fam === 'Playfair Display' && weight === '700'))) {
    console.log(`PRELOAD ${fam} ${weight}: ${url}`);
  }
}
